{{- if and .Values.ad.enabled (not .Values.ad.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "es-poc-cluster.fullname" . }}-ad-secret
  labels:
    {{- include "es-poc-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  AD_BIND_PASSWORD: {{ .Values.ad.bindPassword | quote }}
{{- end }}
