apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimlp-search.fullname" . }}
  labels:
    {{- include "aimlp-search.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "aimlp-search.selectorLabels" . | nindent 4 }}
    role: data
  ports:
    - name: {{ include "aimlp-search.httpScheme" . }}
      port: 9200
      targetPort: 9200
