apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-poc-cluster.fullname" . }}
  labels:
    {{- include "es-poc-cluster.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "es-poc-cluster.selectorLabels" . | nindent 4 }}
    role: data
  ports:
    - name: {{ include "es-poc-cluster.httpScheme" . }}
      port: 9200
      targetPort: 9200
