{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimlp-search.fullname" . }}-kibana
  labels:
    {{- include "aimlp-search.labels" . | nindent 4 }}
    role: kibana
spec:
  selector:
    {{- include "aimlp-search.selectorLabels" . | nindent 4 }}
    role: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
{{- end }}
