apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimlp-search.fullname" . }}-master-headless
  labels:
    {{- include "aimlp-search.labels" . | nindent 4 }}
    role: master
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "aimlp-search.selectorLabels" . | nindent 4 }}
    role: master
  ports:
    - name: transport
      port: 9300
      targetPort: 9300
