{{- if .Values.pdb.master.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aimlp-search.fullname" . }}-master
  labels:
    {{- include "aimlp-search.labels" . | nindent 4 }}
spec:
  minAvailable: {{ min .Values.pdb.master.minAvailable (int .Values.master.replicas) }}
  selector:
    matchLabels:
      {{- include "aimlp-search.selectorLabels" . | nindent 6 }}
      role: master
{{- end }}
{{- if .Values.pdb.data.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aimlp-search.fullname" . }}-data
  labels:
    {{- include "aimlp-search.labels" . | nindent 4 }}
spec:
  minAvailable: {{ min .Values.pdb.data.minAvailable (int .Values.data.replicas) }}
  selector:
    matchLabels:
      {{- include "aimlp-search.selectorLabels" . | nindent 6 }}
      role: data
{{- end }}
