{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "es-poc-cluster.fullname" . }}
  labels:
    {{- include "es-poc-cluster.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName }}
  duration: {{ .Values.tls.duration }}
  renewBefore: {{ .Values.tls.renewBefore }}
  issuerRef:
    name: {{ .Values.tls.issuerName }}
    kind: Issuer
  dnsNames:
    - {{ include "es-poc-cluster.fullname" . }}-ingest
    - {{ include "es-poc-cluster.fullname" . }}-master-headless
    - {{ include "es-poc-cluster.fullname" . }}-data-headless
    - {{ include "es-poc-cluster.fullname" . }}-ingest-headless
    - {{ include "es-poc-cluster.fullname" . }}-ingest.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "es-poc-cluster.fullname" . }}-master-headless.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "es-poc-cluster.fullname" . }}-data-headless.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "es-poc-cluster.fullname" . }}-ingest-headless.{{ .Release.Namespace }}.svc.cluster.local
    - "*.{{ include "es-poc-cluster.fullname" . }}-master-headless.{{ .Release.Namespace }}.svc.cluster.local"
    - "*.{{ include "es-poc-cluster.fullname" . }}-data-headless.{{ .Release.Namespace }}.svc.cluster.local"
    - "*.{{ include "es-poc-cluster.fullname" . }}-ingest-headless.{{ .Release.Namespace }}.svc.cluster.local"
{{- end }}
